package dsl.Learnings.one.sandbox.test;

/*Generated by MPS */

import javax.swing.SwingUtilities;
import Library.newlib.QuestionBank;
import Library.newlib.QuestionPaper;

public class Begin {


  public Begin() throws Exception {



  }

  public static void main(String[] args) throws Exception {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        try {
          QuestionBank qb = new QuestionBank();
          int ti;
          int si;
          int di;
          int temptype;
          int tempsub;
          int tempdiff;
          String subject;
          String qp_code;
          String[] codes;
          String[] types;
          String[] subjects;
          String[] difficulties;

          // view 
          QuestionPaper qp_b0;
          qp_code = "B";
          qp_b0 = new QuestionPaper(qp_code);
          System.out.println("Section" + "B");
          String type_a0a0b0 = "Word";
          boolean show_choices = false;
          String subject_a0a0a0b0 = "a";
          qp_b0.prepare(type_a0a0b0, subject_a0a0a0b0, "1", "1", false);
          qp_b0.getmarks(0, 0);
          qp_b0.pushSection("B");
          qp_b0.showPaper(qp_b0.code);

        } catch (Exception e) {
        }
      }
    });
  }


}
