package QPManifest.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import dsl.Learnings.one.behavior.AbstractCommand_intf_BehaviorDescriptor;

public class EditManifest_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractCommand_intf_BehaviorDescriptor {
  public EditManifest_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "QPManifest.structure.EditManifest";
  }
}
