package QPManifest.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.execution.util.behavior.IMainClass_BehaviorDescriptor;
import dsl.Learnings.one.behavior.AbstractCommand_intf_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.execution.util.behavior.IMainClass_Behavior;

public class ViewManifest_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IMainClass_BehaviorDescriptor, AbstractCommand_intf_BehaviorDescriptor {
  public ViewManifest_BehaviorDescriptor() {
  }

  public String virtual_getUnitName_4666195181811081431(SNode thisNode) {
    return IMainClass_Behavior.virtual_getUnitName_4666195181811081431(thisNode);
  }

  public boolean virtual_isNodeRunnable_4666195181811081448(SNode thisNode) {
    return IMainClass_Behavior.virtual_isNodeRunnable_4666195181811081448(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "QPManifest.structure.ViewManifest";
  }
}
