package QPManifest.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import Library.newlib.qpManifest;

public class ViewManifest_Behavior {
  public static void init(SNode thisNode) {

  }

  public static String call_getTitle_6582483045192465798(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("title");
  }

  public static void call_setTitle_6582483045192466291(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("title", value);
  }

  public static String call_getSubject_6582483045192466790(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("subject");
  }

  public static void call_setSubject_6582483045192467224(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("subject", value);
  }

  public static String call_getKeywords_6582483045192467596(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("keywords");
  }

  public static void call_setKeywords_6582483045193074996(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("keywords", value);
  }

  public static String call_getAuthor_6582483045193075131(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("author");
  }

  public static void call_setAuthor_6582483045193075137(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("author", value);
  }

  public static String call_getInstition_6582483045193075764(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("creator");
  }

  public static void call_setInstitution_6582483045193075770(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("creator", value);
  }

  public static String call_getExamTitle_6582483045193076645(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("examtype");
  }

  public static void call_setExamTitle_6582483045193076651(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("examtype", value);
  }

  public static String call_getDuration_6582483045193077341(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("time");
  }

  public static void call_setDuration_6582483045193077347(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("time", value);
  }

  public static String call_getMaxMarks_6582483045193078014(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("maxmarks");
  }

  public static void call_setMaxMarks_6582483045193078020(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("maxmarks", value);
  }

  public static String call_getInstructions_6582483045193078432(SNode thisNode) {
    qpManifest qpm = new qpManifest();
    return qpm.getString("instructions");
  }

  public static void call_setInstructions_6582483045193078438(SNode thisNode, String value) {
    qpManifest qpm = new qpManifest();
    qpm.update("instructions", value);
  }
}
