package dsl.Learnings.manifest.traa;

/*Generated by MPS */

import Library.newlib.qpManifest;

public class qpclass {
  public qpclass() {
  }

  public static void main(String[] args) {
    qpManifest qpm;
    qpm = new qpManifest();
    String value = null;
    qpm.update("title", "fgf");
    qpm.update("subject", "Subject");
    qpm.update("keywords", "Keywords");
    qpm.update("author", "Author");
    qpm.update("creator", "Intitute");
    qpm.update("time", "2");
    qpm.update("maxmarks", "100");
    qpm.update("examtype", "Exam");
    qpm.update("instructions", "instrns");
  }
}
