package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Begin_BehaviorDescriptor();
      case 1:
        return new CommandList_BehaviorDescriptor();
      case 7:
        return new EmptyLine_BehaviorDescriptor();
      case 2:
        return new CommentLine_BehaviorDescriptor();
      case 20:
        return new StringName_BehaviorDescriptor();
      case 18:
        return new SetQP_BehaviorDescriptor();
      case 16:
        return new Section_BehaviorDescriptor();
      case 19:
        return new SetQPBlock_BehaviorDescriptor();
      case 8:
        return new EmptyLineSETQP_BehaviorDescriptor();
      case 12:
        return new QTYPE_BehaviorDescriptor();
      case 17:
        return new SectionBlock_BehaviorDescriptor();
      case 9:
        return new EmptyLineSection_BehaviorDescriptor();
      case 11:
        return new Mark_BehaviorDescriptor();
      case 24:
        return new TYPEBlock_BehaviorDescriptor();
      case 21:
        return new Subject_BehaviorDescriptor();
      case 10:
        return new EmptyLineType_BehaviorDescriptor();
      case 13:
        return new RepeatQuestionPaper_BehaviorDescriptor();
      case 6:
        return new Difficulty_BehaviorDescriptor();
      case 15:
        return new RepeatType_BehaviorDescriptor();
      case 14:
        return new RepeatSubject_BehaviorDescriptor();
      case 4:
        return new CommentLineSetQP_BehaviorDescriptor();
      case 3:
        return new CommentLineSection_BehaviorDescriptor();
      case 5:
        return new CommentLineType_BehaviorDescriptor();
      case 22:
        return new SubjectList_BehaviorDescriptor();
      case 25:
        return new TypeList_BehaviorDescriptor();
      case 23:
        return new System_Specifics_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"dsl.Learnings.one.structure.Begin", "dsl.Learnings.one.structure.CommandList", "dsl.Learnings.one.structure.CommentLine", "dsl.Learnings.one.structure.CommentLineSection", "dsl.Learnings.one.structure.CommentLineSetQP", "dsl.Learnings.one.structure.CommentLineType", "dsl.Learnings.one.structure.Difficulty", "dsl.Learnings.one.structure.EmptyLine", "dsl.Learnings.one.structure.EmptyLineSETQP", "dsl.Learnings.one.structure.EmptyLineSection", "dsl.Learnings.one.structure.EmptyLineType", "dsl.Learnings.one.structure.Mark", "dsl.Learnings.one.structure.QTYPE", "dsl.Learnings.one.structure.RepeatQuestionPaper", "dsl.Learnings.one.structure.RepeatSubject", "dsl.Learnings.one.structure.RepeatType", "dsl.Learnings.one.structure.Section", "dsl.Learnings.one.structure.SectionBlock", "dsl.Learnings.one.structure.SetQP", "dsl.Learnings.one.structure.SetQPBlock", "dsl.Learnings.one.structure.StringName", "dsl.Learnings.one.structure.Subject", "dsl.Learnings.one.structure.SubjectList", "dsl.Learnings.one.structure.System_Specifics", "dsl.Learnings.one.structure.TYPEBlock", "dsl.Learnings.one.structure.TypeList"};
}
