package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CommentLineSection_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractSectionCommands_intf_BehaviorDescriptor {
  public CommentLineSection_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.CommentLineSection";
  }
}
