package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CommentLine_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractCommand_intf_BehaviorDescriptor {
  public CommentLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.CommentLine";
  }
}
