package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class CommandList_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public CommandList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.CommandList";
  }
}
