package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Difficulty_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Difficulty_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.Difficulty";
  }
}
