package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EmptyLineType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractTypeCommands_intf_BehaviorDescriptor {
  public EmptyLineType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.EmptyLineType";
  }
}
