package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EmptyLineSETQP_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractSetQPCommands_intf_BehaviorDescriptor {
  public EmptyLineSETQP_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.EmptyLineSETQP";
  }
}
