package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EmptyLine_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractCommand_intf_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.EmptyLine";
  }
}
