package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Mark_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Mark_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.Mark";
  }
}
