package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class QTYPE_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractSectionCommands_intf_BehaviorDescriptor {
  public QTYPE_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.QTYPE";
  }
}
