package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RepeatType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractSectionCommands_intf_BehaviorDescriptor {
  public RepeatType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.RepeatType";
  }
}
