package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SectionBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SectionBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.SectionBlock";
  }
}
