package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.StringLiteral_BehaviorDescriptor;

public class SubjectList_BehaviorDescriptor extends StringLiteral_BehaviorDescriptor {
  public SubjectList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.SubjectList";
  }
}
