package dsl.Learnings.one.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import Library.newlib.QuestionBank;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public class SubjectList_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<String> call_getMenu_7751232820941264588(SNode thisNode, List<String> type) {
    QuestionBank qb = new QuestionBank();
    String[] temp = new String[ListSequence.fromList(type).count()];
    for (int j = 0; j < ListSequence.fromList(type).count(); j++) {
      temp[j] = ListSequence.fromList(type).getElement(j).toString();
    }
    String[] result = null;
    try {
      result = qb.showLoopTypeMenu(temp);
    } catch (Exception e) {
    }
    List<String> resList = ListSequence.fromList(new LinkedList<String>());
    for (int i = 0; i < result.length; i++) {
      ListSequence.fromList(resList).addElement(result[i]);
    }
    return resList;
  }

  public static List<String> call_getMenu_4272570878829838961(SNode thisNode, String type) {
    QuestionBank qb = new QuestionBank();
    String[] result = null;
    try {
      result = qb.showMenu(type, "");

    } catch (Exception e) {
    }
    List<String> resList = ListSequence.fromList(new LinkedList<String>());
    for (int i = 0; i < result.length; i++) {
      ListSequence.fromList(resList).addElement(result[i]);
    }
    return resList;
  }
}
