package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class System_Specifics_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public System_Specifics_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.System_Specifics";
  }
}
