package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class TYPEBlock_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public TYPEBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.TYPEBlock";
  }
}
