package dsl.Learnings.one.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import Library.newlib.QuestionBank;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public class TypeList_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<String> call_getMenu_7751232820940800221(SNode thisNode) {
    QuestionBank qb = new QuestionBank();
    String[] result = null;
    try {
      result = qb.showMenu("", "");

    } catch (Exception e) {
    }
    List<String> resList = ListSequence.fromList(new LinkedList<String>());
    for (int i = 0; i < result.length; i++) {
      ListSequence.fromList(resList).addElement(result[i]);
    }
    return resList;
  }
}
