package dsl.Learnings.one.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.StringLiteral_BehaviorDescriptor;

public class TypeList_BehaviorDescriptor extends StringLiteral_BehaviorDescriptor {
  public TypeList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.Learnings.one.structure.TypeList";
  }
}
