package dsl.learnings.two.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Insert_Constraints extends BaseConstraintsDescriptor {
  public Insert_Constraints() {
    super("dsl.learnings.two.structure.Insert");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("Difficulty", new BasePropertyConstraintsDescriptor("Difficulty", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "Difficulty";
        return (((SPropertyOperations.getInteger(propertyValue)) < 10 && (SPropertyOperations.getInteger(propertyValue)) > 0) ? true : false);
      }
    });
    return properties;
  }
}
