package dsl.learnings.two.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IScope;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;
import dsl.learnings.two.behavior.Report_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Report_Constraints extends BaseConstraintsDescriptor {
  public Report_Constraints() {
    super("dsl.learnings.two.structure.Report");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("list1", new BasePropertyConstraintsDescriptor("list1", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "list1";
        {
          List<String> valid_list = ListSequence.fromList(new LinkedList<String>());
          valid_list = Report_Behavior.call_getMenu_1475003049267352357(node);
          for (int i = 0; i < ListSequence.fromList(valid_list).count(); i++) {
            if ((SPropertyOperations.getString(propertyValue)).equalsIgnoreCase(ListSequence.fromList(valid_list).getElement(i))) {
              return true;
            }
          }
          return false;
        }
      }
    });
    properties.put("list2", new BasePropertyConstraintsDescriptor("list2", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "list2";
        {
          List<String> valid_list = ListSequence.fromList(new LinkedList<String>());
          valid_list = Report_Behavior.call_Menu_1475003049268302347(node, SPropertyOperations.getString(node, "list1"));
          for (int i = 0; i < ListSequence.fromList(valid_list).count(); i++) {
            if ((SPropertyOperations.getString(propertyValue)).equalsIgnoreCase(ListSequence.fromList(valid_list).getElement(i))) {
              return true;
            }
          }
          if (isEmptyString((SPropertyOperations.getString(propertyValue)))) {
            return true;
          }
          return false;
        }
      }
    });
    properties.put("list3", new BasePropertyConstraintsDescriptor("list3", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "list3";
        {
          List<String> valid_list = ListSequence.fromList(new LinkedList<String>());
          valid_list = Report_Behavior.call_Menu_1475003049268429457(node, SPropertyOperations.getString(node, "list1"), SPropertyOperations.getString(node, "list2"));
          for (int i = 0; i < ListSequence.fromList(valid_list).count(); i++) {
            if ((SPropertyOperations.getString(propertyValue)).equalsIgnoreCase(ListSequence.fromList(valid_list).getElement(i))) {
              return true;
            }
          }
          if (isEmptyString((SPropertyOperations.getString(propertyValue)))) {
            return true;
          }

          return false;
        }
      }
    });
    return properties;
  }

  private static boolean isEmptyString(String str) {
    return str == null || str.length() == 0;
  }
}
