package dsl.learnings.two.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class SubjectReference_Constraints extends BaseConstraintsDescriptor {
  public SubjectReference_Constraints() {
    super("dsl.learnings.two.structure.SubjectReference");
  }
}
