package dsl.learnings.two.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IScope;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;
import dsl.learnings.two.behavior.Update_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Update_Constraints extends BaseConstraintsDescriptor {
  public Update_Constraints() {
    super("dsl.learnings.two.structure.Update");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("question_number", new BasePropertyConstraintsDescriptor("question_number", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "question_number";
        {
          List<String> valid_list = ListSequence.fromList(new LinkedList<String>());
          valid_list = Update_Behavior.call_getQuestionNumberMenu_2334151094744355094(node);
          for (int i = 0; i < ListSequence.fromList(valid_list).count(); i++) {
            if ((SPropertyOperations.getInteger(propertyValue)) == Integer.parseInt(ListSequence.fromList(valid_list).getElement(i))) {
              return true;
            }

          }
          return false;
        }
      }
    });
    properties.put("set_field", new BasePropertyConstraintsDescriptor("set_field", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "set_field";
        {
          List<String> valid_list = ListSequence.fromList(new LinkedList<String>());
          valid_list = Update_Behavior.call_getAttributeMenu_2334151094745361642(node);
          for (int i = 0; i < ListSequence.fromList(valid_list).count(); i++) {
            if ((SPropertyOperations.getString(propertyValue)).equalsIgnoreCase(ListSequence.fromList(valid_list).getElement(i))) {
              return true;
            }
          }
          return false;
        }
      }
    });
    return properties;
  }
}
