package dsl.learnings.two.sandbox;

/*Generated by MPS */

import Library.newlib.QuestionBank;

public class ddlClass {
  public ddlClass() {
  }

  public static void main(String[] args) throws Exception {
    QuestionBank qb = new QuestionBank();
    qb.searchBy("type", "type2", "2");
  }
}
