package dsl.learnings.two.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorHint;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {
  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0a, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new DDL_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Delete_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new EmptyLine_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Image_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Insert_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new MultipleChoiceAnswer_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Report_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new SearchBy_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new Update_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new ViewAll_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new WordAnswer_Editor());
      default:
    }
    return Collections.emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.emptyList();
  }



  public Collection<ConceptEditorHint> getHints() {
    return Collections.emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0a = new String[]{"dsl.learnings.two.structure.DDL", "dsl.learnings.two.structure.Delete", "dsl.learnings.two.structure.EmptyLine", "dsl.learnings.two.structure.Image", "dsl.learnings.two.structure.Insert", "dsl.learnings.two.structure.MultipleChoiceAnswer", "dsl.learnings.two.structure.Report", "dsl.learnings.two.structure.SearchBy", "dsl.learnings.two.structure.Update", "dsl.learnings.two.structure.ViewAll", "dsl.learnings.two.structure.WordAnswer"};
}
