package dsl.Learnings.one.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Begin_Constraints extends BaseConstraintsDescriptor {
  public Begin_Constraints() {
    super("dsl.Learnings.one.structure.Begin");
  }
}
