package dsl.learnings.two.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.io.File;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public class Image_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<String> call_pictures_6301226679266628135(SNode thisNode, String folderString) {
    File folder = new File(folderString);
    List<String> RESULT = ListSequence.fromList(new LinkedList<String>());

    File[] listOfFiles = folder.listFiles();
    if (listOfFiles.length == 0) {
    }
    for (File file : listOfFiles) {
      if (file.isFile()) {
        ListSequence.fromList(RESULT).addElement("file:\\\\\\" + file.getPath());

      }
    }
    return RESULT;
  }

  public static String call_getbasepath_6301226679266628197(SNode thisNode) {
    String path = "C:\\Users\\" + System.getProperty("user.name") + "\\Pictures\\QUBA";
    File directory = new File(path);
    if (!(directory.exists())) {
      directory.mkdir();
    }

    return path;
  }
}
