package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Image_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements InsertPicture_intf_BehaviorDescriptor {
  public Image_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.Image";
  }
}
