package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class MultipleChoiceAnswer_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Answer_intf_BehaviorDescriptor {
  public MultipleChoiceAnswer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.MultipleChoiceAnswer";
  }
}
