package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Report_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements DDLBLOCK_intf_BehaviorDescriptor {
  public Report_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.Report";
  }
}
