package dsl.learnings.two.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public class Report_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<String> call_getMenu_1475003049267352357(SNode thisNode) {
    List<String> options = ListSequence.fromList(new LinkedList<String>());
    ListSequence.fromList(options).addElement("subject");
    ListSequence.fromList(options).addElement("type");
    ListSequence.fromList(options).addElement("difficulty");
    return options;


  }

  public static List<String> call_Menu_1475003049268302347(SNode thisNode, String s1) {
    List<String> options = ListSequence.fromList(new LinkedList<String>());
    options = Report_Behavior.call_getMenu_1475003049267352357(thisNode);
    ListSequence.fromList(options).removeElement(s1);
    return options;
  }

  public static List<String> call_Menu_1475003049268429457(SNode thisNode, String s1, String s2) {
    List<String> options = ListSequence.fromList(new LinkedList<String>());
    options = Report_Behavior.call_getMenu_1475003049267352357(thisNode);
    ListSequence.fromList(options).removeElement(s1);
    ListSequence.fromList(options).removeElement(s2);
    return options;
  }
}
