package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SearchBy_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements DDLBLOCK_intf_BehaviorDescriptor {
  public SearchBy_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.SearchBy";
  }
}
