package dsl.learnings.two.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;
import Library.newlib.QuestionBank;

public class SearchBy_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<String> call_getContextMenu_2334151094741406800(SNode thisNode) {
    List<String> options = ListSequence.fromList(new LinkedList<String>());
    ListSequence.fromList(options).addElement("subject");
    ListSequence.fromList(options).addElement("type");
    ListSequence.fromList(options).addElement("difficulty");
    return options;
  }

  public static List<String> call_getValueMenu_2334151094741482713(SNode thisNode, String context) {
    QuestionBank qb = new QuestionBank();
    List<String> resList = ListSequence.fromList(new LinkedList<String>());
    try {
      String[] result = qb.searchByMenu(context);
      for (int i = 0; i < result.length; i++) {
        ListSequence.fromList(resList).addElement(result[i]);
      }
    } catch (Exception e) {
    }
    return resList;
  }
}
