package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SubjectReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SubjectReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.SubjectReference";
  }
}
