package dsl.learnings.two.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Update_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements DDLBLOCK_intf_BehaviorDescriptor {
  public Update_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "dsl.learnings.two.structure.Update";
  }
}
